### PR TITLE
Travis Build Passing for python 2.7 & 3.6

### PR DESCRIPTION
**Pull request by ayushkalani**
Link to the travis-ci build
[https://travis-ci.org/ayushkalani/people](url)
All the dependencies can be added in the requirements.txt for building the project.
Please add what more to do, how can I contribute more?
Please approve this pull request.

### CODE REVIEW

**Comment by mayukhnair** [comment]
Hey, your PR looks perfect. Just change the Build status widget to reflect that of ashoka-cs/people. That's it.

**Comment by ayushkalani** [comment]
@mayukhnair  can you please send me the link to your repository?

**Comment by mayukhnair** [comment]
https://github.com/ashoka-cs/people

**Comment by ayushkalani** [comment]
The link to your travis-ci

**Comment by ayushkalani** [comment]
Please approve this pull request then only it will build, approve it then you can change the link accordingly

**Comment by ayushkalani** [comment]
Please merge.

**Comment by mayukhnair** [comment]
This is perfect, though you are sending your pull request into the `master` branch while all code-related PRs are meant to be for the `dev` branch. Nonetheless, I'll merge your PR into `master`.

Thank you so much for working on this issue!

**Pull request merged**
